'''
The Nodes Module

Provides the class definition of different CFG (AST) nodes
'''


# AST Node Types
from control_flow_graph.node_processor.nodes.ContractDefinition import ContractDefinition
from control_flow_graph.node_processor.nodes.ExpressionStatement import ExpressionStatement
from control_flow_graph.node_processor.nodes.FunctionDefinition import FunctionDefinition
from control_flow_graph.node_processor.nodes.IfStatement import IfStatement
from control_flow_graph.node_processor.nodes.PragmaDirective import PragmaDirective
from control_flow_graph.node_processor.nodes.SourceUnit import SourceUnit
from control_flow_graph.node_processor.nodes.VariableDeclaration import VariableDeclaration
from control_flow_graph.node_processor.nodes.VariableDeclarationStatement import VariableDeclarationStatement
from control_flow_graph.node_processor.nodes.WhileStatement import WhileStatement
from control_flow_graph.node_processor.nodes.ForStatement import ForStatement
from control_flow_graph.node_processor.nodes.DoWhileStatement import DoWhileStatement
from control_flow_graph.node_processor.nodes.Assignment import Assignment
from control_flow_graph.node_processor.nodes.BinaryOperation import BinaryOperation
from control_flow_graph.node_processor.nodes.Identifier import Identifier
from control_flow_graph.node_processor.nodes.Literal import Literal
from control_flow_graph.node_processor.nodes.FunctionCall import FunctionCall
from control_flow_graph.node_processor.nodes.UnaryOperation import UnaryOperation
from control_flow_graph.node_processor.nodes.Return import Return 
from control_flow_graph.node_processor.nodes.Conditional import Conditional
from control_flow_graph.node_processor.nodes.MemberAccess import MemberAccess
from control_flow_graph.node_processor.nodes.Throw import Throw
from control_flow_graph.node_processor.nodes.EnumDefinition import EnumDefinition
from control_flow_graph.node_processor.nodes.StructDefinition import StructDefinition

# Solidity >= 0.8 nodes
from control_flow_graph.node_processor.nodes.UncheckedBlock import UncheckedBlock
from control_flow_graph.node_processor.nodes.Block import Block
from control_flow_graph.node_processor.nodes.EmitStatement import EmitStatement
from control_flow_graph.node_processor.nodes.RevertStatement import RevertStatement
from control_flow_graph.node_processor.nodes.TryStatement import TryStatement

# Expression-level nodes
from control_flow_graph.node_processor.nodes.expression_nodes import TupleExpression
from control_flow_graph.node_processor.nodes.expression_nodes import IndexAccess

# Contract-level declarations and statement-level skip nodes
from control_flow_graph.node_processor.nodes.skip_nodes import EventDefinition
from control_flow_graph.node_processor.nodes.skip_nodes import ErrorDefinition
from control_flow_graph.node_processor.nodes.skip_nodes import ModifierDefinition
from control_flow_graph.node_processor.nodes.skip_nodes import UsingForDirective
from control_flow_graph.node_processor.nodes.skip_nodes import PlaceholderStatement
from control_flow_graph.node_processor.nodes.skip_nodes import InlineAssembly
from control_flow_graph.node_processor.nodes.skip_nodes import BreakStatement
from control_flow_graph.node_processor.nodes.skip_nodes import ContinueStatement